# Generated by Django 5.1.1 on 2024-09-25 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_education_graduation_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='gpa',
            field=models.CharField(max_length=90),
        ),
    ]
