# Generated by Django 5.1.1 on 2024-09-25 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_skill_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='category',
            field=models.TextField(),
        ),
    ]
